name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Sadece main branch'e push yapıldığında çalışır

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace API Key Placeholder
        run: |
          # macOS/BSD sed ile uyumluluk için -i '' kullanılır. Linux'ta -i yeterlidir.
          # GitHub Actions Ubuntu kullandığı için -i yeterli olacaktır.
          find ./services -type f -name "*.ts" -exec sed -i "s|GEMINI_API_KEY_PLACEHOLDER|${{ secrets.GEMINI_API_KEY }}|g" {} +
        
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /dist
